### ISSUE TITLE
after recent update nothing works annymore

### ISSUE THREAD

**Issue by dagochen** [dieck/prio3#15]
prio lists are imported but outpot after /rw or looting is imcomplete

**Comment by dieck** [comment]
I removed the last version from releases and will look into it later today

**Comment by dieck** [comment]
I have run multiple instances now and cannot find any hard issues.

I will put out a new version now (minor upgrade for the new WoW classic addon version number). If you encounter any issues, can you please turn on debug and provide some log copies / screenshots? Thank you!
