### ISSUE TITLE
Chatoutput

### ISSUE THREAD

**Issue by kellervermietung** [dieck/prio3#17]
Hyya, 
first of all, thank you so much for your addon. It is really awesome!

Unfortunately I have some issues with the addon. More  precise with its chatoutput:

 

Scenario one: I am the first one to loot the boss/post the loot in raidchat:

Loot and Prios get announced just fine. Additionally, the addon posts twi weird lines (picture 1, red mark)
https://cdn.discordapp.com/attachments/502566608795992065/795396073703079986/1.JPG

Scenario two: I am not the first one to post priorities:

As seen in the picture below, the addon just posts some item links and numbers:
https://cdn.discordapp.com/attachments/502566608795992065/795396147400409088/2.JPG

Any ideas?

**Comment by dieck** [comment]
That looks very much like the Exorsus Raid Tools output for loot.

If you use that addon, please look if /ert, Loot to chat, "Enable linking loot from bosses to the chat" is enabled.

**Comment by dieck** [comment]
Closing for now, I don't think this output is from Prio3 addon
