### ISSUE TITLE
Prio3 doesn't show up

### ISSUE THREAD

**Issue by faize1** [dieck/prio3#5]
Installed the addon a few times now -> at the character screen -> addons -> it could be enabled and disabled 

but in game -> menu -> interface -> addons -> there is no prio3 addon - so theres no chance to make it work

**Comment by dieck** [comment]
Hi!

That's very odd.

Can you try installing the "Swatter" addon and see if any errors regarding Prio3 come up during login already?

Best regards,
Marco

**Comment by faize1** [comment]
Date: 2020-08-17 12:55:32
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\prio3.lua line 1:
   Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceSerializer-3.0".
Debug:
   [C]: ?
   [C]: ?
   ...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:189: EmbedLibrary()
   ...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:171: EmbedLibraries()
   ...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:138: NewAddon()
   Prio3\prio3.lua:1: in main chunk


Date: 2020-08-17 12:55:32
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\iteminfo.lua line 3:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\iteminfo.lua:3: in main chunk


Date: 2020-08-17 12:55:32
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\priorities.lua line 4:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\priorities.lua:4: in main chunk


Date: 2020-08-17 12:55:32
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\loot.lua line 7:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\loot.lua:7: in main chunk


Date: 2020-08-17 12:55:32
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\gui.lua line 3:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\gui.lua:3: in main chunk


Date: 2020-08-17 12:55:32
ID: 6
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\yesno.lua line 3:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\yesno.lua:3: in main chunk


Date: 2020-08-17 12:55:32
ID: 7
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\comms.lua line 4:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\comms.lua:4: in main chunk


Date: 2020-08-17 12:55:32
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\queries.lua line 5:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\queries.lua:5: in main chunk


Date: 2020-08-17 12:55:32
ID: 9
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\core.lua line 27:
   attempt to index global 'Prio3' (a nil value)
Debug:
   [C]: ?
   Prio3\core.lua:27: in main chunk

**Comment by dieck** [comment]
Oh, yes, that library AceSerializer-3.0 is really missing.
I will add it to Prio3 asap.

Why this didn't come up with me, or any other user, so far:
If there is another addon that uses AceSerializer-3.0, and it's loaded before Prio3, the error won't come up. And as the Ace library is widely used, this might be the case more often than not.

**Comment by faize1** [comment]
thank you very much for your response =)
