### ISSUE TITLE
AceConfigDialog-3.0

### ISSUE THREAD

**Issue by Bartinus** [dieck/prio3#7]
Have this Problem and Installed the Addon 10 times or more and still dont work

Date: 2020-08-21 15:30:12
ID: 6
Error occured in: Global
Count: 1
Message: ..\AddOns\Prio3\core.lua line 38:
   Cannot find a library instance of "AceConfigDialog-3.0".
Debug:
   (tail call): ?
   [C]: error()
   ...nterface\AddOns\!Swatter\Libs\SlideBar\SlideMain.lua:63: LibStub()
   Prio3\core.lua:38:
      Prio3\core.lua:27
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:63

**Comment by dieck** [comment]
Hi!
Took me a while to figure it out, seems it's a matter of order of loading the Ace libraries.
Is fixed in the next release.

This won't come up as long as other Ace-powered addons with the same dependencies are also loaded, so that's why most people didn't notice.
